theme: jekyll-theme-hacker

title: MInfo e.V. Hackathon
description: "Ein Hackathon für die Nutzung öffentlicher Daten"
show_downloads: false

footer: |
  <a href="mailto:minfo@mathematik.uni-marburg.de">E-Mail</a>
  &bull; <a href="https://discordapp.com/invite/aKnp9ee" target="_new">Discord</a>
  &bull; <a href="https://www.instagram.com/matheinfo/" target="_new">Instagram</a>
  &bull; <a href="https://www.facebook.com/MatheInfo" target="_new">Facebook</a>
  &bull; <a href="/imprint">Impressum & Datenschutzerklärung</a>
