theme: jekyll-theme-hacker

title: MInfo e.V. Hackathon
description: "Ein Hackathon für die Nutzung öffentlicher Daten"
show_downloads: false

footer: |
  Kontakt: <a href="mailto:minfo@mathematik.uni-marburg.de">minfo@mathematik.uni-marburg.de</a>
  &bull; <a href="/imprint">Impressum & Datenschutzerklärung</a>